### ISSUE TITLE
here lack of a ,

### ISSUE THREAD

**Issue by Geo123abc** [kaylai/fO2bufferplotter#1]
https://github.com/kaylai/fO2bufferplotter/blob/2cd397438370772d7b76a6753ad28b3433002152/create_plot.py#L23

it's an excellent work. 
but after having try, I found a little mistake.
at the right  of 'SiSiO2', there lack of a ","

**Comment by kaylai** [comment]
Good catch! Fixed in commit 13f13d9ff496c8700075118715fd048171678b1f
